include $(GOROOT)/src/Make.$(GOARCH)

TARG=redis
GOFILES=\
	reflect.go\
	future.go\
	specification.go\
	error.go\
	redis.go\
	protocol.go\
	connection.go\
	synchclient.go\
    asynchclient.go\
        
include $(GOROOT)/src/Make.pkg

